task 2.14.3
tacya9/JS-1-2 pull request #62
Opened 2023-06-21 09:54 UTC by tacya9

2023-06-21 16:34 UTC, github-mix approved these changes

2023-06-21 16:34 UTC, github-mix commented on 2.14/2.14.3/index.html
> +Вывести алерт с сообщение: "Вы ввели цифру Х"
X is number, not text

2023-06-21 16:34 UTC, github-mix commented on 2.14/2.14.3/index.html
> +			alert('Вы ввели цифру ноль');
in each case, you have the phrase which starts from 'Вы ввели цифру'. Can we make a separate variable with this value?
And then try to rewrite your code in order to have only one place with the function 'alert"

2023-06-21 16:35 UTC, github-mix requested changes

2023-06-21 16:35 UTC, github-mix commented on 2.14/2.14.3/index.html
> +Вывести алерт с сообщение: "Вы ввели цифру Х"
.

2023-06-22 06:35 UTC, tacya9 commented on 2.14/2.14.3/index.html
> +Вывести алерт с сообщение: "Вы ввели цифру Х"
add comments txt file

2023-06-22 06:46 UTC, github-mix approved these changes

2023-06-22 06:48 UTC, merged